import { describe, it, expect, afterEach } from "vitest";
import {
  buildUsage,
  buildMsg,
  scrubPrompt,
  unscrubResponse,
} from "../../stream.js";
import {
  acquireOpenClawLoopback,
  resetOpenClawLoopbackCache,
} from "../../openclaw-loopback.js";
import { MODEL_CATALOG } from "../../catalog.js";
import { binarySearchTrigger } from "../../healthcheck.js";
import { deriveTurnSessionKey, resolveSessionKey } from "../../session-key.js";

describe("buildUsage", () => {
  it("returns zeroed usage when called with undefined", () => {
    const usage = buildUsage();
    expect(usage.input).toBe(0);
    expect(usage.output).toBe(0);
    expect(usage.cacheRead).toBe(0);
    expect(usage.cacheWrite).toBe(0);
    expect(usage.totalTokens).toBe(0);
  });

  it("maps raw token fields correctly", () => {
    const raw = {
      input_tokens: 100,
      output_tokens: 50,
      cache_read_input_tokens: 25,
      cache_creation_input_tokens: 10,
    };
    const usage = buildUsage(raw);
    expect(usage.input).toBe(100);
    expect(usage.output).toBe(50);
    expect(usage.cacheRead).toBe(25);
    expect(usage.cacheWrite).toBe(10);
  });

  it("totalTokens equals the sum of all four fields", () => {
    const raw = {
      input_tokens: 100,
      output_tokens: 50,
      cache_read_input_tokens: 25,
      cache_creation_input_tokens: 10,
    };
    const usage = buildUsage(raw);
    expect(usage.totalTokens).toBe(185);
  });

  it("cost is always zero (Max subscription)", () => {
    const raw = { input_tokens: 1000, output_tokens: 500 };
    const usage = buildUsage(raw);
    expect(usage.cost).toEqual({
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
      total: 0,
    });
  });

  it("handles partial raw object with missing fields", () => {
    const raw = { input_tokens: 42 };
    const usage = buildUsage(raw);
    expect(usage.input).toBe(42);
    expect(usage.output).toBe(0);
    expect(usage.cacheRead).toBe(0);
    expect(usage.cacheWrite).toBe(0);
    expect(usage.totalTokens).toBe(42);
  });
});

describe("buildMsg", () => {
  const model = {
    api: "anthropic-messages",
    provider: "glueclaw",
    id: "glueclaw-opus",
  };
  const usage = buildUsage();

  it("returns correct shape", () => {
    const msg = buildMsg(model, "hello", usage);
    expect(msg.role).toBe("assistant");
    expect(msg.api).toBe("anthropic-messages");
    expect(msg.provider).toBe("glueclaw");
    expect(msg.model).toBe("glueclaw-opus");
    expect(msg.stopReason).toBe("stop");
  });

  it("content is [{ type: 'text', text }]", () => {
    const msg = buildMsg(model, "hello world", usage);
    expect(msg.content).toEqual([{ type: "text", text: "hello world" }]);
  });

  it("timestamp is approximately Date.now()", () => {
    const before = Date.now();
    const msg = buildMsg(model, "test", usage);
    const after = Date.now();
    expect(msg.timestamp).toBeGreaterThanOrEqual(before);
    expect(msg.timestamp).toBeLessThanOrEqual(after);
  });

  it("passes usage through unchanged", () => {
    const custom = buildUsage({ input_tokens: 99, output_tokens: 1 });
    const msg = buildMsg(model, "x", custom);
    expect(msg.usage.input).toBe(99);
    expect(msg.usage.output).toBe(1);
  });
});

describe("scrubPrompt", () => {
  it("replaces 'personal assistant running inside OpenClaw'", () => {
    const input = "You are a personal assistant running inside OpenClaw.";
    expect(scrubPrompt(input)).toBe(
      "You are a personal assistant running inside GlueClaw.",
    );
  });

  it("replaces HEARTBEAT_OK", () => {
    expect(scrubPrompt("token: HEARTBEAT_OK")).toBe("token: GLUECLAW_ACK");
  });

  it("replaces reply_to_current", () => {
    expect(scrubPrompt("action: reply_to_current")).toBe(
      "action: reply_current",
    );
  });

  it("replaces [[reply_to:", () => {
    expect(scrubPrompt("use [[reply_to:user]]")).toBe("use [[reply:user]]");
  });

  it("replaces openclaw.inbound_meta", () => {
    expect(scrubPrompt("field: openclaw.inbound_meta")).toBe(
      "field: glueclaw.inbound_meta",
    );
  });

  it("replaces 'generated by OpenClaw'", () => {
    expect(scrubPrompt("This was generated by OpenClaw")).toBe(
      "This was generated by GlueClaw",
    );
  });

  it("handles empty string", () => {
    expect(scrubPrompt("")).toBe("");
  });

  it("passes through text with no triggers", () => {
    const safe = "Just a normal prompt with no detection patterns.";
    expect(scrubPrompt(safe)).toBe(safe);
  });

  it("handles multiple triggers in one string", () => {
    const input =
      "personal assistant running inside OpenClaw with HEARTBEAT_OK and reply_to_current";
    const expected =
      "personal assistant running inside GlueClaw with GLUECLAW_ACK and reply_current";
    expect(scrubPrompt(input)).toBe(expected);
  });

  it("does not modify file paths containing 'openclaw'", () => {
    const path = "~/.openclaw/config.json";
    expect(scrubPrompt(path)).toBe(path);
  });

  it("does not modify URLs containing 'openclaw'", () => {
    const url = "https://openclaw.example.com/api";
    expect(scrubPrompt(url)).toBe(url);
  });

  it("replaces multiple occurrences of the same trigger", () => {
    const input = "HEARTBEAT_OK and also HEARTBEAT_OK";
    expect(scrubPrompt(input)).toBe("GLUECLAW_ACK and also GLUECLAW_ACK");
  });
});

describe("unscrubResponse", () => {
  it("reverses GLUECLAW_ACK to HEARTBEAT_OK", () => {
    expect(unscrubResponse("token: GLUECLAW_ACK")).toBe("token: HEARTBEAT_OK");
  });

  it("reverses reply_current to reply_to_current", () => {
    expect(unscrubResponse("action: reply_current")).toBe(
      "action: reply_to_current",
    );
  });

  it("reverses [[reply: to [[reply_to:", () => {
    expect(unscrubResponse("use [[reply:user]]")).toBe("use [[reply_to:user]]");
  });

  it("handles empty string", () => {
    expect(unscrubResponse("")).toBe("");
  });

  it("passes through text with no scrubbed tokens", () => {
    const text = "Just a normal response.";
    expect(unscrubResponse(text)).toBe(text);
  });

  it("handles multiple tokens in one string", () => {
    const input = "GLUECLAW_ACK with reply_current and [[reply:x]]";
    const expected = "HEARTBEAT_OK with reply_to_current and [[reply_to:x]]";
    expect(unscrubResponse(input)).toBe(expected);
  });
});

describe("acquireOpenClawLoopback (env fast path)", () => {
  const origPort = process.env.__GLUECLAW_MCP_PORT;
  const origToken = process.env.__GLUECLAW_MCP_TOKEN;
  const origDist = process.env.OPENCLAW_DIST_DIR;
  const origNodePath = process.env.NODE_PATH;

  afterEach(() => {
    resetOpenClawLoopbackCache();
    if (origPort !== undefined) process.env.__GLUECLAW_MCP_PORT = origPort;
    else delete process.env.__GLUECLAW_MCP_PORT;
    if (origToken !== undefined) process.env.__GLUECLAW_MCP_TOKEN = origToken;
    else delete process.env.__GLUECLAW_MCP_TOKEN;
    if (origDist !== undefined) process.env.OPENCLAW_DIST_DIR = origDist;
    else delete process.env.OPENCLAW_DIST_DIR;
    if (origNodePath !== undefined) process.env.NODE_PATH = origNodePath;
    else delete process.env.NODE_PATH;
  });

  it("returns handle from env vars when both are set", async () => {
    process.env.__GLUECLAW_MCP_PORT = "3456";
    process.env.__GLUECLAW_MCP_TOKEN = "secret123";
    const result = await acquireOpenClawLoopback();
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.source).toBe("env");
      expect(result.handle).toEqual({ port: 3456, token: "secret123" });
    }
  });

  it("ignores env when port is missing", async () => {
    delete process.env.__GLUECLAW_MCP_PORT;
    process.env.__GLUECLAW_MCP_TOKEN = "secret123";
    delete process.env.OPENCLAW_DIST_DIR;
    process.env.NODE_PATH = "";
    const result = await acquireOpenClawLoopback();
    if (result.ok) expect(result.source).not.toBe("env");
  });

  it("ignores env when token is missing", async () => {
    process.env.__GLUECLAW_MCP_PORT = "3456";
    delete process.env.__GLUECLAW_MCP_TOKEN;
    delete process.env.OPENCLAW_DIST_DIR;
    process.env.NODE_PATH = "";
    const result = await acquireOpenClawLoopback();
    if (result.ok) expect(result.source).not.toBe("env");
  });

  it("rejects non-numeric port from env", async () => {
    process.env.__GLUECLAW_MCP_PORT = "not-a-port";
    process.env.__GLUECLAW_MCP_TOKEN = "secret";
    delete process.env.OPENCLAW_DIST_DIR;
    process.env.NODE_PATH = "";
    const result = await acquireOpenClawLoopback();
    if (result.ok) expect(result.source).not.toBe("env");
  });

  it("parses port as integer from env", async () => {
    process.env.__GLUECLAW_MCP_PORT = "8080";
    process.env.__GLUECLAW_MCP_TOKEN = "tok";
    const result = await acquireOpenClawLoopback();
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.handle.port).toBe(8080);
      expect(typeof result.handle.port).toBe("number");
    }
  });
});

describe("MODEL_CATALOG", () => {
  it("has exactly 3 entries", () => {
    expect(MODEL_CATALOG).toHaveLength(3);
  });

  it("every entry has required fields: id, name, provider, contextWindow", () => {
    for (const entry of MODEL_CATALOG) {
      expect(entry.id).toBeTruthy();
      expect(entry.name).toBeTruthy();
      expect(entry.provider).toBeTruthy();
      expect(entry.contextWindow).toBeGreaterThan(0);
    }
  });

  it("every entry has input array containing 'text'", () => {
    for (const entry of MODEL_CATALOG) {
      expect(entry.input).toEqual(expect.arrayContaining(["text"]));
    }
  });

  it("opus and sonnet have reasoning: true", () => {
    const opus = MODEL_CATALOG.find((m) => m.id.includes("opus"));
    const sonnet = MODEL_CATALOG.find((m) => m.id.includes("sonnet"));
    expect(opus?.reasoning).toBe(true);
    expect(sonnet?.reasoning).toBe(true);
  });

  it("all provider fields match 'glueclaw'", () => {
    for (const entry of MODEL_CATALOG) {
      expect(entry.provider).toBe("glueclaw");
    }
  });
});

describe("binarySearchTrigger", () => {
  it("returns the offending line when trigger is in first half", async () => {
    const lines = ["safe line 1", "BADWORD here", "safe line 3", "safe line 4"];
    const testFn = async (chunk: string) => !chunk.includes("BADWORD");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("BADWORD here");
  });

  it("returns the offending line when trigger is in second half", async () => {
    const lines = [
      "safe line 1",
      "safe line 2",
      "safe line 3",
      "TRIGGER at end",
    ];
    const testFn = async (chunk: string) => !chunk.includes("TRIGGER");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("TRIGGER at end");
  });

  it("returns null when entire prompt passes", async () => {
    const lines = ["safe line 1", "safe line 2", "safe line 3"];
    const testFn = async () => true;
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBeNull();
  });

  it("narrows to single line containing the trigger", async () => {
    const lines = Array.from({ length: 20 }, (_, i) =>
      i === 13 ? "line13bad" : `safe line ${i}`,
    );
    const testFn = async (chunk: string) => !chunk.includes("line13bad");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("line13bad");
  });

  it("calls testFn O(log n) times, not O(n)", async () => {
    let callCount = 0;
    const lines = Array.from({ length: 100 }, (_, i) =>
      i === 50 ? "hidden-trigger" : `safe line ${i}`,
    );
    const testFn = async (chunk: string) => {
      callCount++;
      return !chunk.includes("hidden-trigger");
    };
    await binarySearchTrigger(lines, testFn);
    // log2(100) ≈ 7, plus initial full-prompt test and some overhead
    expect(callCount).toBeLessThan(20);
  });

  it("handles single-line input that triggers", async () => {
    const testFn = async (chunk: string) => !chunk.includes("X");
    const result = await binarySearchTrigger(["X"], testFn);
    expect(result).toBe("X");
  });

  it("handles empty input", async () => {
    const testFn = async () => true;
    const result = await binarySearchTrigger([], testFn);
    expect(result).toBeNull();
  });

  it("handles trigger on the first line", async () => {
    const lines = ["TRIGGER", "safe", "safe", "safe"];
    const testFn = async (chunk: string) => !chunk.includes("TRIGGER");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("TRIGGER");
  });

  it("handles trigger on the last line", async () => {
    const lines = ["safe", "safe", "safe", "TRIGGER"];
    const testFn = async (chunk: string) => !chunk.includes("TRIGGER");
    const result = await binarySearchTrigger(lines, testFn);
    expect(result).toBe("TRIGGER");
  });
});

describe("resolveSessionKey", () => {
  it("prefers sessionKey over everything else", () => {
    expect(
      resolveSessionKey({
        sessionKey: "telegram:dm:+34xxx",
        sessionId: "abc-uuid",
        agentDir: "/home/x/.openclaw/agents/eva",
      }),
    ).toBe("telegram:dm:+34xxx");
  });

  it("falls back to sessionId when sessionKey is absent", () => {
    expect(
      resolveSessionKey({
        sessionId: "conv-uuid-1",
        agentDir: "/home/x/.openclaw/agents/eva",
      }),
    ).toBe("conv-uuid-1");
  });

  it("falls back to agentDir when sessionKey and sessionId are absent", () => {
    expect(
      resolveSessionKey({
        agentDir: "/home/x/.openclaw/agents/eva",
      }),
    ).toBe("/home/x/.openclaw/agents/eva");
  });

  it("falls back to 'default' when nothing is provided", () => {
    expect(resolveSessionKey({})).toBe("default");
  });

  it("yields distinct keys for two conversations of the same agent (the bug fix)", () => {
    const agentDir = "/home/x/.openclaw/agents/eva";
    const a = resolveSessionKey({
      sessionKey: "telegram:dm:userA",
      agentDir,
    });
    const b = resolveSessionKey({
      sessionKey: "telegram:dm:userB",
      agentDir,
    });
    expect(a).not.toBe(b);
  });

  it("yields the same key across turns of one conversation (resumption stability)", () => {
    const ctx = {
      sessionKey: "telegram:group:abc:user:def",
      sessionId: "rotating-uuid-on-reset",
      agentDir: "/home/x/.openclaw/agents/eva",
    };
    expect(resolveSessionKey(ctx)).toBe(resolveSessionKey(ctx));
  });

  it("treats empty string as a valid value (does not skip to fallback)", () => {
    // Empty strings are unlikely in practice but we should not silently
    // collapse them — only undefined triggers fallback.
    expect(
      resolveSessionKey({
        sessionKey: "",
        sessionId: "would-be-skipped",
      }),
    ).toBe("would-be-skipped");
  });
});

describe("deriveTurnSessionKey", () => {
  function userMsg(text: string) {
    return { role: "user" as const, content: [{ type: "text", text }] };
  }

  it("returns undefined when agentId is missing", () => {
    expect(
      deriveTurnSessionKey({
        messages: [userMsg("[agent-link · from=waka · msgId=al-1 · thread=chiki↔waka]")],
      }),
    ).toBeUndefined();
  });

  it("returns undefined when no recognised signal is present", () => {
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        systemPrompt: "Generic prompt with no agent-link / chat_id / spawn block.",
        messages: [userMsg("just a plain message body")],
      }),
    ).toBeUndefined();
  });

  it("derives an agent-link session key from the inbound header", () => {
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        messages: [
          userMsg(
            "[agent-link · from=waka · msgId=al-mozg9sv1-7420ds7p · thread=chiki↔waka]\n\n{\"tipo\":\"factura_ingesta\"}",
          ),
        ],
      }),
    ).toBe("agent:chiki:agent-link:direct:waka");
  });

  it("finds the agent-link header even when followed by a metadata user message (OpenClaw 2026.5.6+)", () => {
    // OpenClaw 2026.5.6+ splits a turn into the inbound body plus a
    // trailing `Conversation info` metadata block, both as role=user.
    // The agent-link header lives in the body (older) message; the
    // metadata block is the most recent user message. The function must
    // scan every trailing user message, not only the last one.
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        messages: [
          userMsg(
            "[agent-link · from=waka · msgId=al-mozpvwkf-96rssgx7 · thread=chiki↔waka]\n\nbody payload",
          ),
          userMsg(
            'Conversation info (untrusted metadata):\n```json\n{\n  "chat_id": "waka",\n  "message_id": "al-mozpvwkf-96rssgx7",\n  "sender_id": "waka"\n}\n```',
          ),
        ],
      }),
    ).toBe("agent:chiki:agent-link:direct:waka");
  });

  it("derives the agent-link key when the header carries in_reply_to", () => {
    // Replies from the peer keep the same `from=<peer>` token, so the
    // session key must stay stable across turns of the same conversation.
    expect(
      deriveTurnSessionKey({
        agentId: "roy",
        messages: [
          userMsg(
            "[agent-link · from=evacastro · msgId=al-mozihea8-zwmp8391 · in_reply_to=al-mozigw7y-g5zq5b2d · thread=roy↔evacastro]\n↪ Tu envío anterior (msgId al-…, hace 23s):\n> texto\n\nACK-DIAG-EVA",
          ),
        ],
      }),
    ).toBe("agent:roy:agent-link:direct:evacastro");
  });

  it("does not falsely match a Telegram payload that mentions agent-link in body", () => {
    // The agent-link branch is anchored to start-of-text; a Telegram
    // message that quotes "agent-link" mid-body must not divert to the
    // wrong key. The chat_id branch should still pick this up.
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        messages: [
          userMsg(
            'Hi, I read about [agent-link · from=...] in the docs.\n```json\n{"chat_id": "telegram:540382330"}\n```',
          ),
        ],
      }),
    ).toBe("agent:chiki:telegram:direct:540382330");
  });

  it("derives a Telegram direct chat key from chat_id JSON (regression)", () => {
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        messages: [
          userMsg('```json\n{"chat_id": "telegram:8426343632"}\n```'),
        ],
      }),
    ).toBe("agent:chiki:telegram:direct:8426343632");
  });

  it("derives a Telegram supergroup key from a -100… chat_id (regression)", () => {
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        messages: [
          userMsg('```json\n{"chat_id": "telegram:-1005229099225"}\n```'),
        ],
      }),
    ).toBe("agent:chiki:telegram:supergroup:5229099225");
  });

  it("derives the legacy spawn key from `Agent 2 (target) session:` (regression)", () => {
    expect(
      deriveTurnSessionKey({
        agentId: "evacastro",
        systemPrompt:
          "Agent-to-agent message context\nAgent 1 (requester) session: agent:roy:main\nAgent 2 (target) session: agent:evacastro:main",
      }),
    ).toBe("agent:evacastro:main");
  });

  it("prefers the legacy spawn key over the agent-link header when both are present", () => {
    // Defence in depth: if a future pipeline somehow surfaces both
    // signals at once, the explicit `Agent 2 (target) session:` line is
    // authoritative because it is constructed by the gateway, not by a
    // plugin's user-facing prompt.
    expect(
      deriveTurnSessionKey({
        agentId: "chiki",
        systemPrompt:
          "Agent 2 (target) session: agent:chiki:custom:scope",
        messages: [userMsg("[agent-link · from=waka · msgId=al-1 · thread=chiki↔waka]")],
      }),
    ).toBe("agent:chiki:custom:scope");
  });
});
